### ISSUE TITLE
Fix AboutUs images

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#33]
AboutUs.html images are not showing, try fixing the the src linking. 

Submit Pull request for merging your new branch

**Comment by binHarby** [comment]
@Moutasim02  lets add our images to the AboutUs so we can close this

**Comment by rahaf2201** [comment]
Done! Added all missing images to the images folder.

**Comment by binHarby** [comment]
@rahaf2201  great, closing this
