### ISSUE TITLE
Add Search Filters to BrowsePhotos

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#36]
add the SearchQuery.html filtering

**Comment by binHarby** [comment]
So the task is copy paste SearchQuery.html  content into BrowsePhotos  before the gallery/grid

**Comment by Moutasim02** [comment]
Yes, but try to adapt it to BrowseVideo

**Comment by binHarby** [comment]
Browse photos you mean

**Comment by Moutasim02** [comment]
Yeah it's just adding whatever in the searchquery filters in the browsephotos..

**Comment by binHarby** [comment]
@AlyafeiAli @Moutasim02  Done, Closing this
