### ISSUE TITLE
Fix ShoppingCart layouts and CSS imports

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#40]
Layout is messy and need fix, also colors should be the same as standard

**Comment by binHarby** [comment]
You list three issues here @Moutasim02  under one issue/bug, if we could separate those to different issues it would be better. But lets address them with detail, but keep in mind the items of the cart in this page is based on the user state when reaching this page, in terms of clicked items.

1. layout: Seems similar to the original design. Do you have a problem with ShoppingCart Design? if yes, then please suggest a new design in the group (frankly we should be beyond design changes at this point if we want working site, instead we should have design implementation critiques) . If you believe is not a faithful representation of the design, please elaborate more on how either here or in private channel.

2.  CSS Imports: You only added "css imports" to title, i don't see more details. But i guess it could be the bootstrap 5.3-alpha import ? please confirm

3. Color: Agreed, that is valid

**Comment by Moutasim02** [comment]
Alright I checked again and it seems some issues were on my end because I had an unstable 4G connection at the time of filing the issues, So the layout is fine, CSS imports are just related to the layout, so you can ignore it, the only thing that needs fix atm is the color.

**Comment by Moutasim02** [comment]
@binHarby Sorry for the multiple issues by the way, initially I was classifying them into the pages

**Comment by binHarby** [comment]
I think you its an issue that we don't state the Bootstrap version specifically. We should maybe have a requirments.txt sort of file, where we list the versions for each library we use, for documentation as well to when building the site in the future with webpack or vite

**Comment by binHarby** [comment]
@Moutasim02  No worries

**Comment by Moutasim02** [comment]
Although I already suggested that in the meetings, initially, it was 5.2.3, let us stay on that, we don't need the bleeding edge.

**Comment by binHarby** [comment]
yeah that is right. I'll added it to the documentation here, but once we move to reactjs package.json should do the trick

**Comment by Moutasim02** [comment]
This issue seems to be solved already, so I will close it and it can be opened later if needed
