### ISSUE TITLE
Enhancements to SignUp

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#41]
Seems too crowded, maybe try making it removing some fields, like confirm password and national id or phone number

**Comment by Moutasim02** [comment]
![image](https://github.com/SpecialProjectADU/Site/assets/23410040/2792dff3-2090-4e19-93d5-bacd01420c53)
@rahaf2201 @binHarby This screen needs rework based on the same approach as logging in, The base code should be following the existing code of Login.html. 

As a type of UX enhancement, users for sure won't be able to have their IDs in the first time they enter the website, and by this we are eliminating global user registration, for the **confirm password**, this is the trend now, it's no more required, phone number can be optional too.

**Comment by binHarby** [comment]
Okay I agree with that it does is diverges or is different from the original design, the signup design is relativly similar to the login, with two columns being in center. @Moutasim02 @rahaf2201 

But on the other issue you mention, I don't agree. 
As far as the UAE ID, the project is meant for national level not global. We can debate this on Whatsapp, but for the sake of finishing and the coming demo with H.H office, i say we keep it.

moreover  the UAE ID, it will limit initial bot accounts, limit inappropiate content posts, and provide better integrations with existing government services that would help the website become more official and government oriented .

**Comment by binHarby** [comment]
lets discuss the uae id more on whatsapp with the Dr and the group @Moutasim02

**Comment by binHarby** [comment]
@AlyafeiAli  do you think 'confirm password' on signup is not required ?

**Comment by AlyafeiAli** [comment]
> @AlyafeiAli do you think 'confirm password' on signup is not required ? I still see it with some websites tbh
> 
> Also this is a design modification @Moutasim02 disagreement on this should've been stated earlier

it's better to keep it as that's what the userbase are familiar with and comfortable with..   
the trend nowadays is to ditch it, but I only saw this trend in few websites, and the majority are still using it..  
we don't want to confuse the userbase.. they may feel that something is wrong when they don't see the second field lol

**Comment by binHarby** [comment]
okay, lets try be similar to the design then. This seems to be appropriate action to solve this bug @rahaf2201

**Comment by Moutasim02** [comment]
I agree with whatever suggested earlier, and believe we can proceed with it without any problem

**Comment by binHarby** [comment]
Hmm , good point. a third party login would bypass providing the UAE ID. lets revisit this when we do the actual third party  login integrations

**Comment by rahaf2201** [comment]
A lot of going back and forth on different decisions but I did my best on trying to fix things so here are the new Sign Up and Login Pages on how they look like:

![image](https://github.com/SpecialProjectADU/Site/assets/73061653/57b548e5-9d88-488a-b370-0a7211a3bd5f)
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/b16efd99-e255-4189-ac4e-4da9abd786e9)

**Comment by Moutasim02** [comment]
@rahaf2201 I believe Sign Up is fine, and by the way, I already fixed Log in before, and included some icons for third-party sign-in/up, I believe you can take their code and just apply it to your design, and keep the colors as of the standard colors.

https://github.com/SpecialProjectADU/Site/blob/master/docs/Standards.md

**Comment by binHarby** [comment]
@Moutasim02  close this or ?
