### ISSUE TITLE
UserSettings layout gets corrupted due to inappropriate alignment.

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#46]
Something wrong with the code of this page, if you add any element above that first <form> element it will change the whole layout, better migrate to bootstrap gridding

**Comment by binHarby** [comment]
Okay its screen responsiveness/responsive design issue that could be solved with bootstrap grid system

**Comment by binHarby** [comment]
You want both the columns to stack between before the `md` breakpoint?

**Comment by Moutasim02** [comment]
The problem was on the extra empty tags presented before the normal code starts, if you remove those tags or add a header for example, all layout will change, it's like a 2 column word editor.

**Comment by fatimaalneyadi** [comment]
I fixed it

**Comment by fatimaalneyadi** [comment]
<img width="1162" alt="Screen Shot 2023-05-12 at 9 08 46 PM" src="https://github.com/SpecialProjectADU/Site/assets/124872010/1b7a8821-6123-4348-8e4e-1650da434b98">
