### ISSUE TITLE
Main Page Sticky Navbar 

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#53]
![navBarLooksWrong](https://user-images.githubusercontent.com/34486934/235360630-22286053-94e5-450d-b6f3-0ce3d1d0da21.png)

Mid page logic needs to be fixed.  Nothing in the Navbar shows when scrolling over, due to the font color and the transparent background. Maybe fix the nav bar after scrolling to be similar to his?

![navbar2](https://user-images.githubusercontent.com/34486934/235360754-f448fccd-8fb5-4785-89b8-831b4cd7e3be.png)

**Comment by AlyafeiAli** [comment]
I cannot reproduce the issue on my end... Could the issue be from github?

**Comment by binHarby** [comment]
Hmm, leave this for now then, I'll dev tool it later and see why

**Comment by AlyafeiAli** [comment]
> Hmm, leave this for now then, I'll dev tool it later and see why

I think I found the issue https://github.com/SpecialProjectADU/Site/blob/956d0471edbf5e8f179897571491b833f4b0f5eb/index.html#L14  
It needs to be capitalized
