### ISSUE TITLE
Audio Background

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#56]
![changeTheBackround](https://user-images.githubusercontent.com/34486934/235361516-c643970b-6476-4ed7-a291-dc22b66cd52f.png)
Change the grey background color here so that it matches the standard

**Comment by binHarby** [comment]
The white as well

**Comment by Alyazi010** [comment]
unclear can you please specify the code and which code is for what example: 
container -> #EEEEEE.
