### ISSUE TITLE
Main Page Gallery Tabs Transition Bug

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#57]
Perhaps a change in StyleIndex.css or Script.js Caused the on click event that changes the background from "Most Popular" to other tabs ? @AlyafeiAli  might have some insight on this issue  #48  merged pull request

**Comment by binHarby** [comment]
![MainPageBug](https://user-images.githubusercontent.com/34486934/235362307-7e0a4d1f-509f-42a7-9190-cdd58b198abc.png)

**Comment by AlyafeiAli** [comment]
I'll look into it

**Comment by AlyafeiAli** [comment]
Same as #53 , It works fine locally on my end... This is getting weird tbh

**Comment by binHarby** [comment]
Okay. I'll dev tool this one also.

**Comment by binHarby** [comment]
Fixed issue with #59  merge
