### ISSUE TITLE
Add the site new navbar to Signup

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#62]
Can be copied from Browse Users page

**Comment by Guru6163** [comment]
Hey, I would like to work on this.
Can I get Assigned?

**Comment by binHarby** [comment]
@AlyafeiAli  @Moutasim02

**Comment by rahaf2201** [comment]
Fixed!
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/244b8747-9a33-4909-84ed-62878f70a5b9)
