### ISSUE TITLE
User settings footer

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#69]
Copy footer from Browse Users, make sure to also copy the general css files, Footer Navbar and Global

**Comment by Moutasim02** [comment]
Alright I fixed the whole thing, and rewrote the form to be mobile-friendly, with this, I fixed #69 #67 and #68 which are similar.

**Comment by fatimaalneyadi** [comment]
Moutasim so this means that you have already fixed these ? if you did so how can i review the fixed code?

**Comment by Moutasim02** [comment]
@fatimaalneyadi Yes this is already fixed, you can check out to UserSettingsFooter branch, and have a look, but you can see this screenshot too.
![image](https://github.com/SpecialProjectADU/Site/assets/23410040/9fce5b94-97de-4f3a-a4cd-1faacb28d706)

**Comment by fatimaalneyadi** [comment]
<img width="1160" alt="Screen Shot 2023-05-12 at 9 18 05 PM" src="https://github.com/SpecialProjectADU/Site/assets/124872010/954901bb-74ab-4d56-993a-dcd405c83ae1">

**Comment by Moutasim02** [comment]
@fatimaalneyadi You can fix the icons over my work, I didn't notice the missing icons in my branch until now, that's due to the use of an inappropriate font awesome icons version from your side, please follow the standard, we are only using version 4.7 as you can see from most <head> sections in all pages.

**Comment by fatimaalneyadi** [comment]
@Moutasim02 I did fixed the icons but when i run it the layout didn't appear the same as ur screenshoot although i have input the global, footer, navbar, and user setting css. Do you know how can i fix it, maybe i missed something 
<img width="1470" alt="Screen Shot 2023-05-13 at 1 32 12 PM" src="https://github.com/SpecialProjectADU/Site/assets/124872010/f902ee1c-1d26-4acc-84a0-1bfab08a7caa">

**Comment by Moutasim02** [comment]
@fatimaalneyadi Better make a new branch from master as abdullah already merged UserSettingsFooter branch, and from that one you can push the changes and make a PR.

**Comment by fatimaalneyadi** [comment]
<img width="1388" alt="Screen Shot 2023-05-15 at 2 02 44 PM" src="https://github.com/SpecialProjectADU/Site/assets/124872010/d7fb361c-7daf-4809-8673-1c5d784d500a">

**Comment by binHarby** [comment]
Solved with #79
