### ISSUE TITLE
site wide bootstrap 5.3-alpha  script tag 

### ISSUE THREAD

**Issue by binHarby** [SpecialProjectADU/Site#72]
the following tag, seems to be in most pages , it should be changed to 5.2.3

```html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>
```

**Comment by rahaf2201** [comment]
so it should be as follows: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>, am I right?
