### ISSUE TITLE
Browse photos filter missing

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#85]
Add the filter for the page

**Comment by AlyafeiAli** [comment]
Is the current filter finalized ? (The one in BrowseVideo)  
If not, I think it's better to finalize it first before adding to other pages.. What do you guys think? @binHarby @Moutasim02

**Comment by Moutasim02** [comment]
@AlyafeiAli Videos page filter needs some enhancements as in #84
