### ISSUE TITLE
Users Page Enhancements

### ISSUE THREAD

**Issue by AlyafeiAli** [SpecialProjectADU/Site#89]
### These comments are from Dr. Mourad.  

- Rename Photographers
- Add filters
- Site Wide

**Comment by AlyafeiAli** [comment]
Kindly explain the points, @Moutasim02   
Do you mean to replace the current names or to add new names instead of John Doe's ?  
Filters based on what exactly?

**Comment by Moutasim02** [comment]
@AlyafeiAli 

- Rename the page to Photographers or Browse Photographers rather than "Users" -> With this we need to change Users on the **header>explore** site-wide too.

- Adding filters based on the location of the photographers and any other important filters you find suitable
