### ISSUE TITLE
About-Us Page Enhancements

### ISSUE THREAD

**Issue by AlyafeiAli** [SpecialProjectADU/Site#90]
### These comments are from Dr. Mourad.  

- Rename about Zode
- Add heading (About Zode)
- Replace images

Responsibility: @rahaf2201  and her team.  
Write your questions in the comments and mention Mouatism.

![image](https://github.com/SpecialProjectADU/Site/assets/52626961/f5761740-ab6f-4daa-b37b-324f09f20a1d)

**Comment by rahaf2201** [comment]
Are the first 2 comments the same? @Moutasim02

**Comment by rahaf2201** [comment]
Fixed.
Added heading and downloaded image in the images folder.
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/a435a4a2-b564-4a10-8a12-0ff49a9783d6)

**Comment by rahaf2201** [comment]
Fixed.
Changed About Us -> About Zode in the navbar of all of my group's pages.
Added heading.
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/9cf54f3d-f8ed-4139-8f6b-ce1bba90867e)

**Comment by rahaf2201** [comment]
Fixed.
Changed About Us -> About Zode in the navbar of all of my group's pages.
Added heading.
Added the images in the images folder.
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/adcc6f6b-6083-42dd-94b2-ad2c52e9a1e5)
